#variable 
na8me="srimathikalpana"
age=16
school="SRK"
std="12th"
place="salem"
dob="20.05.2006"

print("name",na8me)
print("age",age)
print("school",school)
print("place",place)
print("std",std)
print(dob)
print(type(na8me))
print(type(age))
print(type(std))
print(type(school))
print(type(place))
print(type(dob))